# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: CmdLine@2
  inputs:
    script: 'git clone https://github.com/jwarren01/Test.git $(Build.SourcesDirectory)\Test'
- task: UseYuniqlCLI@1
  inputs:
    version: 'latest'
- task: RunYuniqlCLI@1
  inputs:
    version: 'latest'
    connectionString: 'Server=tcp:grover-central-reporting.database.windows.net,1433;Initial Catalog=CentralReporting;Persist Security Info=False;User ID=dbadmin;Password=4E(2Y9VB7!w)/]uS;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;'
    workspacePath: '$(Build.SourcesDirectory)\Test'
    targetPlatform: 'SqlServer'
    additionalArguments: '--debug'
